; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env]
extra_scripts = pre:lib/.fetch_deps.py

[env:OC_teensy40]
platform = teensy@4.15.0 ; https://github.com/platformio/platform-teensy/releases
framework = arduino
board = teensy40
build_flags = -DUSB_MIDI_SERIAL -D_GLIBCXX_USE_C99 -I./lib/ -Wdouble-promotion ;-D TEENSY_OPT_SMALLEST_CODE
board_build.f_cpu = 600000000L
lib_deps = 
    https://ehx.spdns.org/squares-and-circles/lib/machine_OC40_latest.zip
    ./lib/stmlib/
    ./lib/braids/
    ./lib/plaits/
    ./lib/rings/
    ./lib/peaks/
    ./lib/open303/
    ./lib/fv1/
lib_ldf_mode = off
build_src_filter = 
    +<*> 
    -<../src/main_TU.cxx>

[env:TU_teensy32]
platform = teensy
framework = arduino
board = teensy31
build_flags = -DUSB_SERIAL -DMACHINE_TU_REV12 -I./lib/ -Wdouble-promotion -Wfloat-conversion
board_build.f_cpu = 120000000L
lib_deps = 
    https://ehx.spdns.org/squares-and-circles/lib/machine_TU32_latest.zip
    ./lib/stmlib/
lib_ldf_mode = off
build_src_filter = 
    +<../src/main_TU.cxx>
    +<../lib/braids/resources.cc>
    +<../lib/peaks/>
    +<../lib/peaks.cxx>
    +<../lib/braids/settings.cc>
    +<../src/voltage.cxx>
    +<../src/midiMonitor.cxx>
    +<../src/midiClock.cxx>
    +<../src/modulations.cxx>
    +<../src/quantizer.cxx>
    +<../src/seq_acid.cxx>
    +<../src/seq_trig.cxx>
