import base64
import math, struct
from array import array

a = "AH9BQSIcAH8JGSlGAD9AQEA/AH8CDAJ/AEZJSUkxACAQCAQCAAZJSSkeAD5BQUE+AAZJSSkeAABEfUAAAEhUVFQgAH8IBAR4AAgICAgIAEF/SUk2AH9BQSIcAAAAAAAAAAAAAAAAAAAAAAAAHD4+PhwcIiIiHBwiIiIcHCIiIhwCAgICAgKCgoKCggICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAoKCgoKCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAuAYBAIBAQY4wAAAAQECBBjgAAAAAPCQkJAQAMCAQECAAIBAQECAAIBAQIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4BgEAgEBAACAgICBgYKEGOAAAAAA8JCQkGAAwAAAAMAAwIBAQIAAgEBAQAAA8IBAQIAAAAAAAAAAAAAAAAAAAwwQIEBAgICAgIBAQCAQDAMAAAAABwAAAAAABwAAAAAAAwUFBQEAAQICAQ8AAAAAAAAAAAAAAAAAAAAAAAAAAAADDBAgQECAgICAgEBAIBAMAwAAAAAHAAAAAAADBAQCBwAHAAAABwADBAQEAgAHAAAABwAAAAAAAAAAAAAAAAAAAAAAgEAgICAgIECAAAAAAAAAAACAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAQCAgICAgQIAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8gQICAhISERCAfAAAAAAAAAAAAPwAAABwiIiIcAD4EAgI8ABwqKioMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHyBAgICEhIJCIB8AAAAAAAAAPyAgEQ4AHCoqKgwAHCIiIhAAECoqKjwADlBQUD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI+A=="
b = "AH9BQSIcAH8JGSlGAD9AQEA/AH8CDAJ/AEZJSUkxACAQCAQCAAZJSSkeAD5BQUE+AAZJSSkeAABEfUAAAEhUVFQgAH8IBAR4AAgICAgIAEF/SUk2AH9BQSIcAAAAAAAAAAAAAAAAAAAAAAAAHD4+PhwcIiIiHBwiIiIcHCIiIhz6+vr6+vr6CtraCvoa6uoa+grq6hr6Cvr6CvoK+vr6+hpqahr66grq6vrqCur6+hrq6hr6Crp6Cvr6+vr6+voCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAv8DAwMDAwMCY5OSkxMC8pOTkmIC4xMSEiICA2JiAgIDAvOTkpNjAvNDgwLyAvMTEyLCAwMi8wMCAwMDAwMD/wAAAAAA4BAIBASEhISIEOAAAAAAAAAA8JCQkGAAwAAAAMAAwIBAQIAAgEBAQAAA8IBAQIAAAAAAAAAAAAAAAAAA/wAAAAAAAAAEBAQEAwAHAAECBAADBAQEAgAAAwMAAAAABwABAgQABwAAAQcABwQEAgEAAAQHBAAAAAAAAAD/AAAAAAADBAgQEBAQEAgEAwAAAAAAAAAHAAAAAAADBAQCBwAHAAAABwADBAQEAgAHAAAABwAAAAAAAAAAAAAAAAD/AACAAAAAAPgICAj4AAAAgEAgEBAQEBCgQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAPz8PBwMDAQEBAQECAgQIMAAAAAAAICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AACARCgQA/wD8AP8AAB8gQIAAAAQCAYBAIB8AAAAAAAAEBAQEBAAQCAQCAQAEBB8EBAAAAAAAAAAAAAAA/wAAH2CAAAAAAAAEBAICAgGBYB8AAAAAPyAgEQ4AHCoqKgwAHCIiIhAAECoqKjwADlBQUD4AAAAAAAAAAAAAAAAA/wAAAAAAAAADAgMCAwAAAAAAAAEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAABAgIEBAQEBAICAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD7+vr6+vr6+vr6+vr6+vr6+vr6+vr6+vr6+vr6+vr6ioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiouIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI+A=="
c = "/////wP3z/cD/w+3u7cP/wf7+/t3/wPf398D///7A/v//wPv378D/wPb29v7////AP////8D29vb+/8D79+/A/8H+9vbF///+wP7//8D79+/A/8D29vb+///////////////////////////////////////////////////////BwcHhkdHR4YHxgcHB8YHx0ZGhgcHBgcHBwYHBwYGBgcHBgcHBwYHBgYGBgYHBwf4BwcHBwaGRoYGBwYHBwcGBwcGBgYGBwdGxgYHBwYHBwcGBwYGBgYGBwcHBwcHB8cHBwfHB8cHBwfHBwcHBwcHBwcHBwcHBwcHBwcHBwcHV/8AAAAPEBISHgAfAQIEHwAfEBAIBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAHwQEBB8AHwIBAR4ACBUVFR4AABAfEAAADhEREQ4ABikpKR8AAAAAAAAAHwICAh8AHwICAh8AAAAAAAAAAAAAAAAAAAAAAAAAAABV/wAAAD5BQUEiAAcYYBgHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAB8EhESfAB8CAQEeAAgVFRUeAAAQX9AAAA4REREOAAYpKSkfAAAAAAAAAB/CAgIfwB/CAgIfwBCYVFJRgAAAAAAAAAAAAAAAAAAAFX/AP//A/v7d4//A9ubW+f/A////wP/A/fP9wP/59vb2zv//////////////////wD/AP///+fb21uH/wf7+/sH/+fb21uH///vC////9+vr69//wPf7+8f/9/f39/f//sD29sn/wP7+3eP//////////////////////////8A/f8ABwf2JsYn9weGh4eHhgfnFhYW5wdml5eXFgfmFhYWJwcHBwcHBwcHBwcHBwcHAP8ABwcHZ5aWl+cH5xYWFucHZ5aWl+cHB0bWBgcHhkZGRgcH9odHR4YHh4eHh4cHZpaWlhcH9hYWJ8cHBwcHBwcHBwcHBwcHBwcHBwcHBwBf/wAAAMdAQEBHAMAAAADAAAMEBAQDAAQEBAQDAAMEBAQCAAAAAAAAAAAAAAAAAAAA/wAAAABARMRCQQDDREREgwCARERCgQCAREdEgACERUVFggAHAAAABwCAQEBAgADEBAQEwwAHBAQCAQCAQEBAgADAAAAAwAAAAAAAAAAAAFX/+Pj4//r6+vj4+P36/fj4+Pj4+Pj4+Pj4+Pj4+Pj4+IiIiIiIiIiIiIiIiIiIiIiPiIiIiIiIj4iIiI+KjoqJiImKioqPiI+IiIiPiImKioqPiIqKioqKiI+IiIiIiI+KioqPiIqKioqKiI+IiIiPiI+KioqPiIiIiIiIiIiI/Q=="
d = "////////ewF/////k5P/////////////fQF9//+DfX19g//v7+/v7/+DfX19u/+DfX19g/8B9+/fAf8B7e3t/f//fQF9//+DfW1tC/////////////////////////////////////////////////////////////////////8DAwMDAwMDQ0PDQ0MDw0NDQ4MDA0PDQwMDg0NDQ4MDAwMDAwMDA0PDQwMDwwMDA8MDw0NDQ4MDwwMDA8MDQ0PDQ0MDAwMDAwMDAwMDAwMDAwMDAwMDQ0PDQ0MDw0NDQ4MDA4PDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDVwAAgAAAAAAAgJ+AAACfAgYKkQAAEB8QAAAPkJKSHgCCAgICggCAkJ+QAACfAQIEnwCfgoKCgQAPEBAQDwAAAB8AAAAAAAAAAAAAAAAAAAAAgICAAAAAgJ+AAACfAgYKkQAAEJ8QAAAAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAD9AAAgEQoEAB8gICARAAMMMAwDAAQEBAQEAAAgPyAAAD8CBAg/AD8EBAQDAB8gICAfAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ICAAAB8gICARAAMMMAwDAAAhPyAAAAAgID8AAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAQF/AQEAfwkZKUYAfBIREnwAfwQIEH8ARklJSTEAfwkJCQYAPkFBQT4ARklJSTEAf0lJSUEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgAQmFRSUYAGBQSfxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAD+BBgE/gAAgv6CAAD+goJEOAAAgv6CAACAgICAgAB8goKCRAD+EBAQ/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAPwQIED8APgEBAT4AAQE/AQEAPwkJCQEAAAAAAAAAPwgICD8APgEBAT4APwAAAAAAPwEBIhwAAAAAAAAAAAAAAAAAAAAAAAAAPwkJCQEAPBIREjwAPwAAAAAABgkJCTEAPwkJCQEAAAAAAAAAAAAAAAAAFf4+Pj4+Pj4+Pj4+Pj4+fj4+Pn4+Pn5+fj4+Pj5+Pj4+YmJiYmIiYmJiYmIiYiIiImIiImJiYiIiYmJiYmIiYmJiIiIiIiIiIiIiIiIiIiIiIiIiIiIiYiIiIiIiYiIiImIiYmJiYmIiYmJiYiIiYmJiYmIiIiIiIiIiIiIiIiI/Q=="
encoder_setup = "////A9vb2/v/A+/fvwP/B/v7+3f/B/v7+wf/A/v7d4//A9vb2/v/A9ubW+f/////////59vb2zv/A9vb2/v/+/sD+/v/A////wP/A9vb2+f/////////////////////////////////////////////////////////////////BwcGBgYGBgcGBwcHBgcHBgYGBwcHBgYGBwcGBgYHBwcGBgYGBgcGBwcHBgcHBwcHBwcGBgYGBwcGBgYGBgcHBwYHBwcHBgYGBwcGBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcH//8AAAAAAAAAAPBQUCAA8FBQoADwUFAQACBQUJAAIFBQkAAAAAAAAPBQUBAA8ECA8ADgEBAQAAAAAAAAEPAQEADgEBDgAAAAAAAA8FBQoADwUFAQAPAAAPAA8FBQEADwUFCgACBQUJAA8FBQEAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAQAAAAABAAABAAEBAQEAAQEBAAABAQEAAAAAAAAAAQEBAQABAAABAAABAQEAAAAAAAAAAQAAAAABAQAAAAAAAAABAAABAAEBAQEAAAEBAAABAQEBAAEAAAEAAQEBAAABAQEBAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAADAMAgEAgIBAf0BAQICBAgwwAAAAADgAAAAAAAAgICAAAAAwCAgQACA4IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwDAIBAICAQH9AQECAgQIMMAAAAAA4CAgIMAAAICgAAAAAICAgIAA4ACAgAAAgOCAAAAAAAAAAAAA//8AAAAAAAcYIECAgAAAAQAAgIBAIBgHAAAAAA8ICAgIAAcKCgoDAAEPAQAAAAAHCAgEAAAAAAAAAAAAAAAAAAAAAAAAAAAHGCBAgIAAAAEAAICAQCAYBwAAAAAPAQMFCAAACA8IAAADFBQUDwAPAQAADwAABwgIBAAAAAAAAAD//wAAAAAAAAAAAAAAAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//+Pj4+Pj4+Pj4+Pj4+IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI/w=="
io_test = "////////+wP7//9/v9/v9/8H+/v7B//////////7+wP7+/8D29vb+//n29vbO//7+wP7+///////////////////////////////////////////////////////////////////////////////////////////////////////BwcHBwcGBgYHBwcHBwcHBwcGBgYHBwcHBwcHBwcHBgcHBwYGBgYGBwYGBgYHBwcHBgcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcH//8AAAAAAgL+AgIA/hIyUowAAIT+gAAAAAAAAAAAfIKCgnwAAABAwAAAAAAAAAAAfIKCgkQADjDAMA4AAIT+gAAAAAAAAAAAEBAQEBAAfIKCgnwAAMDAAAAAfIKCgnwAfIKCgnwAhMKikowADjDAMA4AAAAAAAAAAAAAAAAAAAD//wAAAAAICPgICAD4SMhIMAAQCIhIMAAAAAAAAADwCAgI8AAAAAEAAAAAAAAAAADwCAgIEAA4wADAOAAQCIhIMAAAAAAAAABAQPBAQADwCAgI8AAAAAAAAADwCAgI8ADwCAgI8AAQCIhIMAA4wADAOAAAAAAAAAAAAAAAAAAAAP//AAAAACAg4yAgAOMgICHCACIjomIiAAAAAAAAAMEiIiLBAAAABQMAAAAAAAAAAMEiIiJBAOAAAwDgACIjomIiAAAAAAAAAAAAwQAAAMEiIiLBAAADAwAAAMEiIiLBAMEiIiLBAEIjIiLCAOAAAwDgAAAAAAAAAAAAAAAAAAAA//8AAAAAgICPgIAAj4GDhQgABAgIiQYAAAAAAAAAB4iIiAcAAAAUDAAAAAAAAAAAB4iIiAQAgAMMA4AABAgIiQYAAAAAAAAAAQEHAQEAB4iIiAcAAAwMAAAAB4iIiAcAB4iIiAcACIyKiQgAgAMMA4AAAAAAAAAAAAAAAAAAAAD//wAAAAAAAD8AAAA/BAwUIwAMCgk/CAAAAAAAAAAfICAgHwAAAFAwAAAAAAAAAAAfICAgEQADDDAMAwAMCgk/CAAAAAAAAAAEBB8EBAAfICAgHwAAMDAAAAAfICAgHwAfICAgHwAhMCgkIwADDDAMAwAAAAAAAAAAAAAAAAAAAP//iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIj4+Pj4+Pj4+Pj4+Pj4+IiIiIiIiIiIiIiIiIiI/w=="

screenshots = { "io_test" : io_test, "encoder_setup" : encoder_setup, "engine" : a, "modulation" : b, "menu" : c, "config" : d }

mult4 = lambda n: int(math.ceil(n/4))*4
mult8 = lambda n: int(math.ceil(n/8))*8
lh = lambda n: struct.pack("<h", n)
li = lambda n: struct.pack("<i", n)

def bmp(rows, w):
    h, wB = len(rows), int(mult8(w)/8)
    s, pad = li(mult4(wB)*h+0x20), [0]*(mult4(wB)-wB)
    s = li(mult4(w)*h+0x20)
    return (b"BM" + s + b"\x00\x00\x00\x00\x20\x00\x00\x00\x0C\x00\x00\x00" +
            lh(w) + lh(h) + b"\x01\x00\x01\x00\xff\xff\xff\x00\x00\x00" +
            b"".join([bytes(row+pad) for row in reversed(rows)]))


def getPixel(buffer, x, y):
    return buffer[x + int(y / 8) * 128] & (1 << (y & 7)) == 0

def setPixel(row, x, c):
    if c:
        row[int(x/8)] |= (0b10000000 >> (x % 8))
    else:
        row[int(x/8)] &= ~(0b10000000 >> (x % 8))

for key in screenshots:
    s = base64.b64decode(screenshots[key])
    print(len(s))
    rrr = []
    for y in range(64): # comma, or other
        r = list(s[y*16:][:16])
        for x in range(128):
            setPixel(r, x, getPixel(s, x, y))
        rrr.append(r)

    smile = [[0xFF,0xFF], [0x81,0xFF], [0xA5,0xFF], [0x81,0xFF], [0xA5,0xFF], [0xBD,0xFF], [0x81,0xFF], [0xFF,0xFF]]

    f = open(key + ".bmp", "wb")
    f.write(bmp(rrr, 128))
    f.close()